---
sidebar: sidebar
permalink: air-cleared-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: air.cleared events
---

= air.cleared events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
air.cleared EMS events occur when the Automated Incremental Repair (AIR) subsystem clears an entry in the qtree metafile because of inconsistent data within that entry.

== air.cleared.qtm.entry
*Severity*::
NOTICE
*Description*::
This message occurs when the Automated Incremental Repair (AIR) subsystem clears an entry in the qtree metafile because of inconsistent data within that entry.
*Corrective Action*::
(None).
*Syslog Message*::
Qtree entry certification failed at %s. In the qtree metafile %d, AIR cleared an entry that corresponds to the TID %d in volume %s.
*Parameters*::
*source* (STRING): Location where qtree entry certification failed.
*inode* (INT): Inode number of qtree metafile.
*tid* (INT): TID.
*volume* (STRING): Name of the volume.
