---
sidebar: sidebar
permalink: gb-netra-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: gb.netra events
---

= gb.netra events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
gb.netra EMS events occur when ONTAP encounters issues associated with storage failover (SFO) giveback object store connectivity.

== gb.netra.ca.check.failed
*Severity*::
ERROR
*Description*::
This message occurs during the migration of an aggregate as a part of storage failover (SFO) giveback, when the destination node cannot reach the object stores.
*Corrective Action*::
Verify that your intercluster LIF is online and functional by using the 'network interface show' command. Also, check network connectivity to the object store server by using the 'ping' command over the destination node intercluster LIF. Additionally, verify that the configuration of your object store has not changed and that login and connectivity information is still accurate by using the 'aggregate object-store config show' command. It is possible to override this error by specifying false for the "require-partner-waiting" parameter of the giveback command. For more information or assistance, contact NetApp technical support.
*Syslog Message*::
Giveback of aggregate '%s' (uuid: %s) failed due to %s preventing object store access on the destination node.
*Parameters*::
*vol* (STRING): Name of the aggregate.
*aggr_uuid* (STRING): UUID of the aggregate.
*reason* (STRING): Activity that is preventing the aggregate giveback operation.

== gb.netra.ca.check.failed.oam
*Severity*::
ERROR
*Description*::
This message occurs during the migration of an aggregate as a part of storage failover (SFO) giveback, when the destination node cannot reach the object stores.
*Corrective Action*::
Verify that your intercluster LIF is online and functional by using the 'network interface show' command. Also, check network connectivity to the object store server by using the 'ping' command over the destination node intercluster LIF. Additionally, verify that the configuration of your object store has not changed and that login and connectivity information is still accurate by using the 'aggregate object-store config show' command. It is possible to override this error by specifying false for the "override-destination-checks" parameter of the giveback command. For more information or assistance, contact NetApp technical support.
*Syslog Message*::
Giveback of aggregate '%s' (uuid: %s) failed due to %s preventing object store access on the destination node.
*Parameters*::
*vol* (STRING): Name of the aggregate.
*aggr_uuid* (STRING): UUID of the aggregate.
*reason* (STRING): Activity that is preventing the aggregate giveback operation.
