---
sidebar: sidebar
permalink: license-cert-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: license.cert events
---

= license.cert events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
license.cert EMS events occur when ONTAP encounters issues associated with the license validation certificate.

== license.cert.expired
*Deprecated*::
Deprecated as of version 9.12.1. If the license validation certificate expires, license validation workflows are unaffected and no customer action is required.
*Severity*::
ALERT
*Description*::
This message occurs when the license validation certificate is expired. A new license cannot be validated.
*Corrective Action*::
Contact your sales representative or reseller about renewing your license validation certificate.
*Syslog Message*::
A new license cannot be validated. Certificate expired on %s.
*Parameters*::
*exp_date* (STRING): Expiration date.

== license.cert.expired.check
*Deprecated*::
Deprecated as of version 9.12.1. If the license validation certificate expires, license validation workflows are unaffected and no customer action is required.
*Severity*::
NOTICE
*Description*::
This message occurs when the license validation certificate is near its expiration date. After the certificate expires, a new license cannot be validated.
*Corrective Action*::
Contact your sales representative or reseller about renewing your license validation certificate.
*Syslog Message*::
Certificate to validate licenses will expire on %s.
*Parameters*::
*exp_date* (STRING): Expiration date.
