---
sidebar: sidebar
permalink: lmgr-nl-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: lmgr.nl events
---

= lmgr.nl events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
lmgr.nl EMS events occur when the number of mirrored open lock count reaches the maximum supported limit.

== lmgr.nl.open.limit.hit
*Severity*::
NOTICE
*Description*::
This message occurs when the number of mirrored open lock count reaches the maximum supported limit.
*Corrective Action*::
Run the "vserver locks show-mirrored-open-count -detailed" command to check the mirrored open lock count and try closing the unused files to bring this count down to the currently supported maximum mirrored open locks.
*Syslog Message*::
The number of mirrored open locks count %u has reached the limit %u for pool %s. The current number/limit of other lock manager objects are: files %u/%u hosts %u/%u locks %u/%u owners %u/%u.
*Parameters*::
*nl_locks_total* (INT): Number of mirrored open locks.
*nl_locks_limit* (INT): Maximum supported mirrored open locks.
*pool_name* (STRING): Name of the limit pool.
*files_total* (INT): Number of allocated files in the pool.
*files_limit* (INT): Allocated files limit for the pool.
*hosts_total* (INT): Number of allocated hosts in the pool.
*hosts_limit* (INT): Allocated hosts limit for the pool.
*locks_total* (INT): Number of allocated locks in the pool.
*locks_limit* (INT): Allocated locks limit for the pool.
*owners_total* (INT): Number of allocated owners in the pool.
*owners_limit* (INT): Allocated owners limit for the pool.
