---
sidebar: sidebar
permalink: mgmt-cifsserver-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: mgmt.cifsserver events
---

= mgmt.cifsserver events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== mgmt.cifsserver.failure
*Severity*::
ERROR
*Description*::
This message occurs when a CIFS server fails to be configured and, therefore, CIFS access might not be available.
*Corrective Action*::
Check the reason for the error and take action accordingly. For further assistance, contact technical support.
*Syslog Message*::
Failed to configure CIFS server. Error: %s.
*Parameters*::
*reason* (STRING): Reason for the failure.
*vservername* (STRING): Name of the vserver.
*cifsservername* (STRING): Name of the cifs server.

== mgmt.cifsserver.success
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when a CIFS server is successfully configured after a failure.
*Corrective Action*::
(None).
*Syslog Message*::
(None).
*Parameters*::
*vservername* (STRING): Name of the vserver.
*cifsservername* (STRING): Name of the cifs server.
