---
sidebar: sidebar
permalink: vsdr-volume-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: vsdr.volume events
---

= vsdr.volume events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== vsdr.volume.idconflict
*Severity*::
ERROR
*Description*::
This message occurs when the the volume to be created on the destination cluster fails because of an internal identity conflict with another volume in the system.
*Corrective Action*::
Log in to the source cluster and delete the volume by using the "volume delete" command.
*Syslog Message*::
Configuration replication for volume "%s" in Vserver "%s" has failed because of an internal ID conflict.
*Parameters*::
*volume_name* (STRING): Volume on which this error occurred.
*vserver_name* (STRING): Vserver name for which configuration replication is happening.

== vsdr.volume.name.conflict
*Severity*::
ERROR
*Description*::
This message occurs during a SnapMirror resync(R) operation on a Storage Virtual Machine (SVM) disaster recovery (DR) relationship, when a new volume needs to be created on the destination SVM but another volume with the same name already exists on it, and it is also the destination of a volume-level SnapMirror relationship. The resync operation fails to start.
*Corrective Action*::
Rename the volume on the destination SVM by using the "volume rename" command or delete it by using the "volume delete" command, and then execute another "snapmirror resync" command.
*Syslog Message*::
The volume "%s" is already present in SVM "%s" and it is the destination of a volume-level SnapMirror relationship.
*Parameters*::
*volume_name* (STRING): Name of the volume that the system is trying to replicate into the destination SVM.
*vserver_name* (STRING): SVM name for which the SnapMirror resync was initiated.

== vsdr.volume.sis.on.fail
*Severity*::
ALERT
*Description*::
This message occurs when a Vserver DR subsystem fails to enable volume efficiency on the volume.
*Corrective Action*::
Enable volume efficiency on the destination volume by using the "volume efficiency on" command. For more information, refer to TR-4476.
*Syslog Message*::
Vserver DR: Volume efficiency configuration is not applied on volume %s of Vserver %s. Reason: %s
*Parameters*::
*destination_volume* (STRING): Name of the destination volume of the Vserver DR relationship.
*destination_vserver* (STRING): Name of the destination Vserver of the Vserver DR relationship.
*reason* (STRING): Reason.
