---
sidebar: sidebar
permalink: wafl-watch-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: wafl.watch events
---

= wafl.watch events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
wafl.watch EMS events occur when ONTAP encounters issues associated with WAFL(R) change notify requests.

== wafl.watch.cache.limit.near
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when WAFL(R) "change notify" requests approach the size limit of the inode cache pool. This is caused by an excessive number of "change notify" requests being generated by the Server Message Block(SMB) server. If the maximum limit is reached and the limit is not increased, significant system performance degradation could occur.
*Corrective Action*::
Contact Contact NetApp technical support. for assistance.
*Syslog Message*::
Size of "change notify" requests in inode cache pool: %d, approaching the size limit: %d
*Parameters*::
*current_size* (INT): Current size of the inode cache pool.
*max_size* (INT): Maximum size of the inode cache pool.

== wafl.watch.remote.client.limit
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when when we hit the maximum limit of number of remote watch clients in the system.
*Corrective Action*::
(None).
*Syslog Message*::
The maximum limit of number of remote watch clients is hit.
*Parameters*::
(None).

== wafl.watch.remote.msg.limit
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when when we hit the maximum limit of number of remote watch messages in the system.
*Corrective Action*::
(None).
*Syslog Message*::
The maximum limit of number of remote watch messages is hit.
*Parameters*::
(None).
